[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "aappmart"
version = "0.1.0"
description = "Autonomous Attack Path Prediction & Multi-Agent Red Team Engine"
authors = [
    { name = "secwexen" }
]
readme = "README.md"
requires-python = ">=3.10"
license = { file = "LICENSE" }

dependencies = [
    "networkx",
    "numpy",
    "pandas",
    "scikit-learn",
    "fastapi",
    "uvicorn",
    "rich",
    "pyyaml"
]

[tool.setuptools.packages.find]
where = ["."]
